services:
    redis:
        container_name: redis
        image: redis:8.6
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        ports:
            - 127.0.0.1:6379:6379
        volumes:
            - v-redis:/data

    postgres:
        container_name: postgres
        image: postgres:17
        ports:
            - 127.0.0.1:5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - v-postgres:/var/lib/postgresql/data

    nats:
        container_name: nats
        image: nats:2.12
        command: ["-js", "-m", "8222"]
        ports:
            - 127.0.0.1:4222:4222
            - 127.0.0.1:8222:8222
        volumes:
            - v-nats:/data

volumes:
    v-postgres:
    v-redis:
    v-nats:
